#!/usr/bin/env python
# -*- mode: python -*-

## see README
## this runs in the container, and sets up the testcase

import os
import sys

import tempfile
import functools

from twisted.internet import reactor, defer, task
from twisted.internet.endpoints import TCP4ServerEndpoint
from twisted.web import server, resource
from twisted.python import log

sys.path.insert(0, '/txtorcon')
import txtorcon


log.startLogging(sys.stdout)

def updates(prog, tag, summary):
    p = ('#' * int(10*(prog/100.0))) + ('.'*(10 - int(10*(prog/100.0))))
    print "%s %s" % (p, summary)

@defer.inlineCallbacks
def main(reactor):
    print "Launching Tor"
    tor = yield txtorcon.launch(reactor, progress_updates=updates)
    print "launch over:", proto
    print 'Running "ps afxu":'
    os.system("ps afxu")

task.react(main)
